sequenceDiagram
    participant App as Application
    participant Setup as SetupService
    participant Http as HttpService
    participant Device as ESP32 Device

    App->Setup: Select AP Mode
    Setup->NetworkInfo: connectWithRetries()
    Setup->Http: get('/config')
    Device-->>Http: Response: Device Configuration
    Setup->Http: get('/get_public_key')
    Device-->>Http: Response: RSA Public Key
    alt User selects External AP
        Setup->Http: get('/scan_wifi')
        Device-->>Http: Response: List of WiFi Networks
        App->Setup: connectToWiFi(credentials)
        Setup->Http: post('/connect_wifi', credentials.toJson())
        Device->Device: decrypt_base64_message(credentials)
        Device->ExternalAP: esp_wifi_set_config(ssid, password)
        Device->ExternalAP: esp_wifi_connect()
        Device-->>Http: Response: Connection Status, IP Address, Port
    else User selects Internal AP
        Setup->Http: get('/internal_mode')
        Device-->>Http: Response: IP Address, Port
    end
