name: Flutter Test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cache Flutter dependencies
      uses: actions/cache@v1
      with:
        path: /opt/hostedtoolcache/flutter
        key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}

    - name: Set up Flutter
      if: steps.flutter-cache.outputs.cache-hit != 'true'
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        
    - name: Dart version
      run: dart --version

    - name: Flutter version
      run: flutter --version

    - name: Flutter doctor
      run: flutter doctor

    - name: Install dependencies
      run: flutter pub get

    - name: Run tests
      run: flutter test