name: Windows Build
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Enable windows build
        run: flutter config --enable-windows-desktop
        
      - name: Build Windows
        run: flutter build windows --release

      - name: Verify and Package Build
        run: |
          # Debug current state
          Write-Host "Current directory: $(Get-Location)"
          Write-Host "Build directory structure:"
          Get-ChildItem -Path "build\windows" -Recurse
          
          # Correct path including x64
          $BuildPath = "build\windows\x64\runner\Release"
          Write-Host "Checking build path: $BuildPath"
          
          if (!(Test-Path $BuildPath)) {
              Write-Error "Build directory not found: $BuildPath"
              exit 1
          }
          
          Write-Host "Build directory contents:"
          Get-ChildItem -Path $BuildPath
          
          Write-Host "Creating ZIP archive..."
          Compress-Archive -Path "$BuildPath\*" -DestinationPath "windows-build.zip" -Force
          
          if (!(Test-Path "windows-build.zip")) {
              Write-Error "ZIP file was not created"
              exit 1
          }
          Write-Host "ZIP file created successfully"
        shell: pwsh
        
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-app
          path: windows-build.zip
          
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: windows-build.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}